name: Push commit
on: pull
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          pip list
          pwd
          filename=`date "+%Y%m%d-%s"$RANDOM$RANDOM.md`
          date +%s > content/$filename
          ls
      - name: Commit report
        run: |
          ls
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
