name: Run Playwright Script Manually

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Connect Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:example
        args: --exit-node ubuntu-server
      
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependence
      run: npm install         
    - name: Install Playwright
      run: npx playwright install   
    - name: Run Playwright script
      run: node ./script.js
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: ./example.png
