name: Run Playwright Script Manually

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npm install playwright
    - name: Run Playwright script
      run: node script.js
    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: data/example.png
