name: Push commit
on: 
  schedule:
    - cron:  '5 * * * *'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          python md.py
      - name: Commit report
        run: |
          ls
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
